### PR TITLE
🤪 bugfix (closes #14)  & 📰 correct messages order

### LINKED ISSUE #14: Back end issue
**Describe the bug**
There is an excessive data fetching taking place which exceeds the daily 50k reads Firebase quota. 

**To Reproduce**
It's hard to tell what exactly is causing this exhausting amount of data reads, but it's reproduced by some of the actions:
- Relogin (High probability)
- Chat creation (Medium probability)
- Couple of messages (Low probability)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by neugomonov**

### CODE REVIEW

File: components/CustomListItem.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const CustomListItem = ({ id, chatName, enterChat }) => {
                 setChatMessages(snapshot.docs.map((doc) => doc.data()))
             );
         return unsubscribe;
-    });
+    }, []);
```
Comment (pauket) [inline components/CustomListItem.js:19]: 🐛

Comment (neugomonov) [inline components/CustomListItem.js:19]: 🐛

**Review by pauket — APPROVED** [review]
